### ISSUE TITLE
.NET Framework

### ISSUE THREAD

**Issue by iljadvm** [dancol90/mi-360#15]
Hi dancol90!
I have the problem, when you connect two same xiaomi game-pads and hover the cursor on the tray's icon, the error appears:

![image](https://user-images.githubusercontent.com/15846020/64986325-71c3d480-d8cf-11e9-80b2-7ba0cec4d476.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Text length must be less than 64 characters long.
Parameter name: Text
Actual value was Xiaomi Gamepad XInput manager
◉○○○ - Battery 77%
○◉○○ - Battery N/A.
   at System.Windows.Forms.NotifyIcon.set_Text(String value)
   at mi360.Mi360Application._NotifyIcon_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
mi-360
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Program%20Files/mi-360-2/mi-360.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Nefarius.ViGEmClient
    Assembly Version: 1.15.16.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Program%20Files/mi-360-2/mi-360.exe
----------------------------------------
HidLibrary
    Assembly Version: 3.1.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Program%20Files/mi-360-2/mi-360.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

I will be grateful if you can fix the bug.
Thank you for great program!

**Comment by dancol90** [comment]
Hi! Yeah I've spotted the problem. I'll try to solve it as soon as I can

**Comment by dancol90** [comment]
Moving the discussion to #7
