### ISSUE TITLE
.net framework problem when working with 2 gamepads

### ISSUE THREAD

**Issue by DJoRDJ734** [dancol90/mi-360#7]
![screenshot_7](https://user-images.githubusercontent.com/19380076/53369761-f31c3f80-395c-11e9-9bed-5283af886717.jpg)

**Comment by dancol90** [comment]
That's a language I can't read. And a mere screenshot without a description of the problem won't help, either.

Please attach an English translation of the error and describe what you are trying to achieve.

**Comment by iljadvm** [comment]
Hello, Daniele! I have the same problem, when you connect two gamepads and hover the cursor on the tray`s icon, the error appears.
![изображение](https://user-images.githubusercontent.com/15846020/56939363-8e25c700-6b10-11e9-8639-0bc8b7f89193.png)

```
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Text length must be less than 64 characters long.
> Parameter name: Text
> Actual value was Xiaomi Gamepad XInput manager
> ◉○○○ - Battery 100%
> ○◉○○ - Battery 91%.
>    at System.Windows.Forms.NotifyIcon.set_Text(String value)
>    at mi360.Mi360Application._NotifyIcon_MouseMove(Object sender, MouseEventArgs e)
>    at System.Windows.Forms.NotifyIcon.OnMouseMove(MouseEventArgs e)
>    at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> mi-360
>     Assembly Version: 0.4.0.0
>     Win32 Version: 0.4.0.0
>     CodeBase: file:///C:/Program%20Files/mi-360/mi-360.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Nefarius.ViGEmClient
>     Assembly Version: 1.15.16.0
>     Win32 Version: 0.4.0.0
>     CodeBase: file:///C:/Program%20Files/mi-360/mi-360.exe
> ----------------------------------------
> HidLibrary
>     Assembly Version: 3.1.0.0
>     Win32 Version: 0.4.0.0
>     CodeBase: file:///C:/Program%20Files/mi-360/mi-360.exe
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
```

**Comment by redline99cs** [comment]
hello are 2 controller connected at the same time working?
i want to buy second xiaomi gamepad and not sure after reading this issue
does it affect functionality?
thank you

**Comment by dancol90** [comment]
I've pushed a couple of commits that solves the issues.
Unfortunately, I'm unable to create a new release binary package now.

I hope to be able to release v0.4.1 very soon!

**Comment by DJoRDJ734** [comment]
> Я выдвинул несколько коммитов, которые решают проблемы.
> К сожалению, я не могу создать новый двоичный пакет выпуска сейчас.
> 
> Я надеюсь, что смогу выпустить v0. 4. 1 очень скоро!

nice!) thx

**Comment by iljadvm** [comment]
Thank you! :hand::smile:

**Comment by fixsss** [comment]
> I've pushed a couple of commits that solves the issues.
> Unfortunately, I'm unable to create a new release binary package now.
> 
> I hope to be able to release v0.4.1 very soon!

I hope it will happen sometime, thank you for your support and trying to fix this.

**Comment by dancol90** [comment]
New version released with fixes for this issue!
